apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-{{ .Release.Name }}-ingress
  namespace: amit
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /amit/
            pathType: Prefix
            backend:
              service:
                name: nginx-{{ .Release.Name }}-service
                port:
                  number: 80
