apiVersion: v1
kind: Service
metadata:
  name: nginx-{{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx-custom
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      {{- if eq .Values.service.type "NodePort" }}
            nodePort: {{ .Values.service.port }}
      {{- end }}
