apiVersion: v1
kind: Service
metadata:
  name: nginx-{{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  # annotations:
  #   {{- range $key, $value := .Values.service.annotations }}
  #   {{ $key }}: {{ $value | quote }}
  #   {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx-custom
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      {{- if eq .Values.service.type "NodePort" }}
            nodePort: {{ .Values.service.port }}
      {{- end }}
