pipeline {
    agent any

     parameters {
        string(name: 'TAG', defaultValue: 'jen_def', description: 'Just a tag bro')
    }

    stages {
        stage ('Opening msg'){
            steps {
                echo "hi, gonna change the playbook parameter"
            }
        }

        stage ('Playbook'){
            steps {
                sshagent(credentials: ['EC2_ansible_amit']){
                    sh """
                        cd consul/nginx_port
                        ansible-playbook -i hosts.yaml append_html.yml
                    """
                }
            }
        }

        // Last stage
        
        stage ('Cleaning'){
            steps{
                cleanWs()
            }
        }
    }
}