pipeline {
    agent any

    stages {
        stage ('Open msg'){
            steps {
                echo "Gonna upload my docker to ecs"
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}