AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: amit-cf-s3
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: A bucket created by cloud formation
    Value: !Ref MyS3Bucket
