pipeline {
    agent any

    environment {
        CHANGE = false
    }

    parameters {
        string(name: 'TAG', defaultValue: 'latest', description: 'Nginx tag')
        string(name: 'CHART_NAME', defaultValue: 'custom', description: 'The deployment name is needed to retrieve the current docker image used')
        string(name: 'NAMESPACE', defaultValue: 'amit', description: 'Cluster namespace')
        choice(name: 'SERVICE_TYPE', choices: ['ingress', 'loadbalancer']. description: 'Choose how do you want to load it')
    }

    stages {
        stage ('Echo msg') {
            steps {
                echo "hi, I'm gonna update your nginx image and service type"
                sh "kubectl get nodes"
            }
        }

        stage ('Change service type') {
            when {
                expression { 
                    return SERVICE_TYPE == 'loadbalancer'
                }
            } 
            steps {
                echo "Changing service to ${SERVICE_TYPE}"
                sh """
                    cd ./k8s/nginx-custom/
                    helm upgrade --install ${CHART_NAME} ./nginx-custom/ -f ${SERVICE_TYPE}-values.yaml --set tag=${TAG} -n ${NAMESPACE}
                """
            }
        }

        stage ('Is tag exist?') {
            steps {
                script {
                    def imageName = sh (
                        script: "kubectl get deployment nginx-${CHART_NAME}-deployment -n ${NAMESPACE} -o jsonpath='{.spec.template.spec.containers[0].image}' | awk -F ':' '{print \$1}'",
                        returnStdout: true
                    ).trim()

                    echo "$imageName"

                     def imageExists = sh(
                        script: """
                        curl -s -o /dev/null -w "%{http_code}" https://hub.docker.com/v2/repositories/${imageName}/tags/${TAG}/
                        """,
                        returnStdout: true
                    ).trim()

                    echo "image tag exists return code: $imageExists"

                    if (imageExists == '200') {
                        echo "Docker tag ${TAG} exists for ${imageName}."
                    } else {
                        error "Docker tag ${TAG} does NOT exist for ${imageName}."
                    }
                }
            }
        }

        stage ('Check docker image') {
            steps {
                script {
                    def currentTag = sh(
                        script: "kubectl get deployment nginx-${CHART_NAME}-deployment -n ${NAMESPACE} -o jsonpath='{.spec.template.spec.containers[0].image}' | awk -F ':' '{print \$2}'",
                        returnStdout: true
                    ).trim()

                    echo "$currentTag"

                    if (params.TAG != currentTag) { 
                        CHANGE = true 
                    }
                }
            }
        }

        stage ('Upgrade chart') {
            when {
                expression { 
                    return CHANGE == true
                }
            } 
            steps {
                sh """
                    cd ./k8s/nginx-custom/
                    helm upgrade --install ${CHART_NAME} ./nginx-custom/ -f values.yaml --set tag=${TAG} -n ${NAMESPACE}
                """
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}