- name: Update my A record in Route 53 (amit.aws.cts.care.)
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Set amit.aws.cts.care to new IP
      amazon.aws.route53:
        zone: aws.cts.care
        record: amit.aws.cts.care.
        type: A
        ttl: 300
        value: 51.17.184.174
        state: present
        overwrite: true
