services:
    vault:
        image: hashicorp/vault:1.19
        container_name: vault
        cap_add:
            - IPC_LOCK
        env_file:
            - .env
        ports: 
            - 8200:8200
        volumes:
            - vault_data:/vault/file
        networks:
            - default_net

networks:
    default_net:
        name: default_net
        # external: true

volumes:
    vault_data: