pipeline {
    agent any

    stages {
        stage ('Opening msg') {
            steps {
                echo "Hi, gonna push"
            }
        }

        stage ('Docker build'){
            steps {
                echo "Building"
                sh "cd aws/ecr/nginx"
                sh "docker build -t 314525640319.dkr.ecr.il-central-1.amazonaws.com/amit/nginx:${BUILD_NUMBER} ."
            }
        }

        stage ('Docker push'){
            steps {
                echo "Pushing"
                sh "docker push 314525640319.dkr.ecr.il-central-1.amazonaws.com/amit/nginx:${BUILD_NUMBER}"
            }
        }
    }

    post {
        stage ('Cleanup') {
            steps {
                cleanWs()
            }
        }
    }


    
}